# Generated by Django 5.2.3 on 2026-06-02 05:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('stack', models.CharField(max_length=260)),
                ('portfolio_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('vetted', 'Vetted'), ('paused', 'Paused'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('availability_score', models.PositiveSmallIntegerField(default=5)),
                ('quality_score', models.PositiveSmallIntegerField(default=5)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('service_label', models.CharField(max_length=140)),
                ('budget', models.CharField(max_length=80)),
                ('timeline', models.CharField(max_length=80)),
                ('details', models.TextField()),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('estimated_min', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_max', models.PositiveIntegerField(blank=True, null=True)),
                ('deposit_amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('matched', 'Matched'), ('quoted', 'Quoted'), ('deposit_pending', 'Deposit pending'), ('deposit_paid', 'Deposit paid'), ('in_progress', 'In progress'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='new', max_length=30)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_price', models.PositiveIntegerField()),
                ('max_price', models.PositiveIntegerField(blank=True, null=True)),
                ('deposit_amount', models.PositiveIntegerField()),
                ('monthly', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'service categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('stack', models.CharField(max_length=260)),
                ('portfolio_url', models.URLField()),
                ('converted_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.developerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('stk_sent', 'STK sent'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('merchant_request_id', models.CharField(blank=True, max_length=120)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=120)),
                ('result_code', models.CharField(blank=True, max_length=20)),
                ('result_description', models.TextField(blank=True)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='marketplace.projectrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('system', 'System')], max_length=20)),
                ('recipient', models.CharField(max_length=220)),
                ('subject', models.CharField(blank=True, max_length=220)),
                ('message', models.TextField()),
                ('success', models.BooleanField(default=False)),
                ('provider_response', models.TextField(blank=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.projectrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.servicecategory'),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='service_categories',
            field=models.ManyToManyField(blank=True, to='marketplace.servicecategory'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='suggested', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='marketplace.developerprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='marketplace.projectrequest')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'unique_together': {('project', 'developer')},
            },
        ),
    ]
