# Generated by Django 5.2.3 on 2026-07-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_blogpost_metadata_and_seed_posts'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='idx_payment_status'),
        ),
        migrations.AddIndex(
            model_name='projectrequest',
            index=models.Index(fields=['status'], name='idx_projectrequest_status'),
        ),
    ]
