# Generated by Django 5.2.3 on 2026-07-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_blogpost_metadata_and_seed_posts'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('checkout_request_id', ''), _negated=True), fields=('checkout_request_id',), name='uniq_payment_checkout_request_id'),
        ),
    ]
