# Generated by Django 5.2.3 on 2026-07-15 09:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('billing_address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text="e.g. 'softmarket'", max_length=60, unique=True)),
                ('name', models.CharField(help_text="Display name, e.g. 'SoftMarket Kenya'", max_length=120)),
                ('brand_primary_color', models.CharField(default='#6d28d9', max_length=7)),
                ('brand_accent_color', models.CharField(default='#22d3ee', max_length=7)),
                ('logo_url', models.URLField(blank=True)),
                ('default_lead_owner', models.CharField(blank=True, help_text='Fallback owner name if no territory match.', max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('personal_notes', models.TextField(blank=True)),
                ('lifecycle', models.CharField(choices=[('subscriber', 'Subscriber'), ('lead', 'Lead'), ('customer', 'Customer'), ('churned', 'Churned')], default='subscriber', max_length=20)),
                ('territory', models.CharField(blank=True, help_text='County / region / ZIP for lead routing', max_length=80)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crm.tenant')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('stage', models.CharField(choices=[('prospecting', 'Prospecting'), ('qualification', 'Qualification'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='prospecting', max_length=20)),
                ('amount', models.PositiveIntegerField(default=0, help_text='Deal value in KSh')),
                ('probability', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.account')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.contact')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crm.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('territory', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(choices=[('web_form', 'Website form'), ('referral', 'Referral'), ('cold_outreach', 'Cold outreach'), ('event', 'Event'), ('other', 'Other')], default='web_form', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('bant_budget', models.PositiveSmallIntegerField(default=0, help_text='1-3')),
                ('bant_authority', models.PositiveSmallIntegerField(default=0, help_text='1-3')),
                ('bant_need', models.PositiveSmallIntegerField(default=0, help_text='1-3')),
                ('bant_timeline', models.PositiveSmallIntegerField(default=0, help_text='1-3')),
                ('rating', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('unrated', 'Unrated')], default='unrated', max_length=20)),
                ('owner', models.CharField(blank=True, help_text='Assigned rep (auto or manual)', max_length=120)),
                ('auto_responded', models.BooleanField(default=False)),
                ('converted_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='crm.contact')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crm.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('note', 'Note'), ('task', 'Task')], default='note', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, help_text='For tasks/follow-ups', null=True)),
                ('done', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.contact')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crm.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crm.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('tenant', 'name')},
        ),
    ]
