# Generated by Django 5.2.3 on 2026-07-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['stage', 'order', '-created_at']},
        ),
        migrations.AddField(
            model_name='opportunity',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
