# Generated by Django 5.2.3 on 2026-07-17 09:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_opportunity_options_opportunity_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('mpesa', 'M-Pesa'), ('whatsapp', 'WhatsApp'), ('etims', 'eTIMS'), ('offline', 'Offline sync')], max_length=20, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crm.tenant')),
            ],
            options={
                'ordering': ['channel'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('mpesa', 'M-Pesa'), ('whatsapp', 'WhatsApp'), ('etims', 'eTIMS'), ('offline', 'Offline sync')], max_length=20)),
                ('recipient', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crm.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text="Stable slug, e.g. 'proposal'", max_length=30)),
                ('label', models.CharField(help_text="Display name, e.g. 'Proposal'", max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('probability', models.PositiveSmallIntegerField(default=50, help_text='Default win-probability (%) for the weighted forecast.')),
                ('is_won', models.BooleanField(default=False)),
                ('is_lost', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crm.tenant')),
            ],
            options={
                'ordering': ['tenant', 'order'],
                'unique_together': {('tenant', 'key')},
            },
        ),
    ]
