# Generated by Django 5.2.3 on 2026-07-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_integrationconfig_integrationmessage_tenantstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconfig',
            name='channel',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('whatsapp', 'WhatsApp'), ('etims', 'eTIMS'), ('offline', 'Offline sync')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='integrationconfig',
            unique_together={('tenant', 'channel')},
        ),
    ]
