# Generated by Django 5.2.3 on 2026-07-19 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_integrationconfig_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.opportunity'),
        ),
    ]
