# Generated by Django 5.2.3 on 2026-07-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_integrationconfig_channel_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['tenant', 'type', 'done'], name='idx_activity_tenant_type_done'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant', 'lifecycle'], name='idx_contact_tenant_lifecycle'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'rating'], name='idx_lead_tenant_rating'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['tenant', 'stage'], name='idx_opp_tenant_stage'),
        ),
    ]
