# Generated by Django 5.2.3 on 2026-08-09 23:56

import crm.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_integrationconfig_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='job_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planner', models.CharField(default='playbook', help_text="'claude' when an LLM planned the run, 'playbook' for the deterministic path.", max_length=20)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='running', max_length=10)),
                ('brief', models.TextField(blank=True, help_text='What the agent concluded, for a human.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crm.tenant')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(choices=[('contact', 'Contact'), ('account', 'Account'), ('opportunity', 'Opportunity'), ('lead', 'Lead')], max_length=20)),
                ('subject_id', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('context', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crm.tenant')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='crm.agentrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seq', models.PositiveSmallIntegerField(default=0)),
                ('tool', models.CharField(max_length=60)),
                ('tool_input', models.JSONField(blank=True, default=dict)),
                ('tool_output', models.JSONField(blank=True, default=dict)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('ok', models.BooleanField(default=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='crm.agentrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crm.tenant')),
            ],
            options={
                'ordering': ['run', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(choices=[('contact', 'Contact'), ('account', 'Account'), ('opportunity', 'Opportunity'), ('lead', 'Lead')], max_length=20)),
                ('subject_id', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('research_contact', 'Research contact'), ('enrich_account', 'Enrich account'), ('verify_field', 'Re-verify stale field'), ('review_deal', 'Review deal health'), ('reconcile_payment', 'Reconcile payment'), ('deal_room_signal', 'Follow up on deal-room activity'), ('brief', 'Write a briefing')], max_length=30)),
                ('reason', models.TextField(blank=True, help_text='Why this was scheduled — shown to the rep, in plain words.')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('priority', models.IntegerField(default=0, help_text='Lower runs first.')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=12)),
                ('lease_owner', models.CharField(blank=True, max_length=80)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('scheduled_by_agent', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crm.tenant')),
            ],
            options={
                'ordering': ['priority', 'due_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='agentrun',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='crm.agenttask'),
        ),
        migrations.CreateModel(
            name='DealRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=crm.models.new_room_token, max_length=48, unique=True)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('terms', models.TextField(blank=True)),
                ('next_step', models.CharField(blank=True, max_length=200)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by_name', models.CharField(blank=True, max_length=160)),
                ('accepted_note', models.TextField(blank=True)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal_room', to='crm.opportunity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crm.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealRoomView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('visitor_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('referrer', models.CharField(blank=True, max_length=300)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='crm.dealroom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crm.tenant')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(choices=[('contact', 'Contact'), ('account', 'Account'), ('opportunity', 'Opportunity'), ('lead', 'Lead')], max_length=20)),
                ('subject_id', models.PositiveIntegerField()),
                ('field', models.CharField(help_text="e.g. 'phone', 'industry'", max_length=60)),
                ('value', models.TextField(blank=True)),
                ('source', models.SlugField(help_text="Observation kind, e.g. 'crm.signature-block'", max_length=60)),
                ('source_detail', models.CharField(blank=True, help_text='Where exactly — activity id, URL, payment ref.', max_length=300)),
                ('strength', models.PositiveSmallIntegerField(default=0, help_text='0-100, priced from `source` by the evidence ledger.')),
                ('observed_at', models.DateTimeField(help_text='When the observation was made, not when stored.')),
                ('applied', models.BooleanField(default=False, help_text='True if this observation was written to the record.')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='crm.agentrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crm.tenant')),
            ],
            options={
                'ordering': ['-observed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank transfer'), ('cash', 'Cash')], default='mpesa', max_length=10)),
                ('external_ref', models.CharField(blank=True, max_length=40)),
                ('payer_name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True, help_text='The confirmation as received.')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('needs_review', 'Needs review'), ('ignored', 'Ignored')], default='unmatched', max_length=14)),
                ('match_confidence', models.PositiveSmallIntegerField(default=0)),
                ('match_reason', models.TextField(blank=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='crm.contact')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='crm.opportunity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crm.tenant')),
            ],
            options={
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(choices=[('contact', 'Contact'), ('account', 'Account'), ('opportunity', 'Opportunity'), ('lead', 'Lead')], max_length=20)),
                ('subject_id', models.PositiveIntegerField()),
                ('field', models.CharField(max_length=60)),
                ('current_value', models.TextField(blank=True)),
                ('proposed_value', models.TextField(blank=True)),
                ('rationale', models.TextField(blank=True)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.CharField(blank=True, max_length=120)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='crm.evidence')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='crm.agentrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crm.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agenttask',
            index=models.Index(fields=['tenant', 'status', 'due_at'], name='crm_agentta_tenant__d14721_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttask',
            index=models.Index(fields=['subject_type', 'subject_id'], name='crm_agentta_subject_595443_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['tenant', 'subject_type', 'subject_id', 'field'], name='crm_evidenc_tenant__b33372_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_ref__gt', '')), fields=('tenant', 'external_ref'), name='unique_payment_ref_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['tenant', 'status'], name='crm_suggest_tenant__42ee34_idx'),
        ),
    ]
