# Generated by Django 5.2.3 on 2026-07-19 11:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_activity_opportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=40, unique=True)),
                ('amount_excl_vat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=16.0, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('etims_status', models.CharField(choices=[('not_sent', 'Not submitted'), ('queued', 'Queued'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='not_sent', max_length=12)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='crm.contact')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='crm.opportunity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crm.tenant')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
    ]
