# Generated by Django 5.2.3 on 2026-07-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='billing_pin',
            field=models.CharField(blank=True, help_text='KRA PIN / VAT number for eTIMS', max_length=20),
        ),
    ]
