# Generated by Django 5.2.3 on 2026-07-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_contact_billing_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='access_code',
            field=models.CharField(blank=True, help_text='Client access code for the tenant login gate (plan a).', max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Open to anyone (no login). Untick for paying-client instances.'),
        ),
    ]
