# Generated by Django 5.2.3 on 2026-07-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_tenant_access_code_tenant_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Workspace owner email (set at sign-up).', max_length=254),
        ),
    ]
