# Generated by Django 5.2.3 on 2026-07-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_tenant_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='has_sample_data',
            field=models.BooleanField(default=False, help_text='Tenant is showing the seeded onboarding sample.'),
        ),
    ]
