# Generated by Django 5.2.3 on 2026-08-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_contact_job_title_agentrun_agentquestion_agentstep_and_more'),
        ('crm', '0011_tenantmembership'),
    ]

    operations = [
    ]
